### ISSUE TITLE
Small error in MQTT.md

### ISSUE THREAD

**Issue by scoudibou** [tspopp/AquaMQTT#12]
First of all thank you very much for your contribution. I've an Atlantic one and I'm happy to try it with AquaMQTT in some times.
Waiting for my PCB, so I'm reading the doc and trying to configure MQTT Topics for Home Assistant, I think I've noticed a small error in your last but least line of MQTT.md : 
![image](https://github.com/tspopp/AquaMQTT/assets/108148811/c90566a6-3270-40fd-9a51-c20c011c5b24)
I think it shoulb be $root/ctrl/flagPVModeHeatElement instead of $root/ctrl/flagPVModeHeatPump.

Don't you have a MQTT Template for Home Assistant or a config topic to directly integrate it ?

Anyway thank you a lot !

**Comment by tspopp** [comment]
Hey @scoudibou,

awesome, looking forward to see some some results with your Atlantic heat pump :). Let me know if there is anything I can help you with. In case it won't work out of the box, I am happy to add some more debugging options.

I don't have a clean home assistant / hacs module/template yet, in the meantime I can share you what I've been using , but it is not localized...

Additions to `configuration.yaml`

```yaml

mqtt:
  binary_sensor:
    - name: "Aquawin State Heating Element"
      state_topic: "tortuga/aquamqtt/main/stateElement"
      payload_on: "1"
      payload_off: "0"
      icon: mdi:heating-coil

    - name: "Aquawin State Heatpump"
      state_topic: "tortuga/aquamqtt/main/stateHeatpump"
      payload_on: "1"
      payload_off: "0"
      icon: mdi:heat-pump-outline

    - name: "Aquawin State Fan"
      state_topic: "tortuga/aquamqtt/main/stateFan"
      payload_on: "1"
      payload_off: "0"
      icon: mdi:fan

    - name: "Aquawin State External Boiler"
      state_topic: "tortuga/aquamqtt/main/stateExtBoiler"
      payload_on: "1"
      payload_off: "0"
      icon: mdi:water-boiler

    - name: "Aquawin State Defrost"
      state_topic: "tortuga/aquamqtt/main/stateDefrost"
      payload_on: "1"
      payload_off: "0"
      icon: mdi:snowflake-melt

  sensor:
    - name: "Aquawin Warmwasser IST"
      state_topic: "tortuga/aquamqtt/main/waterTemp"
      unit_of_measurement: "°C"
      state_class: measurement

    - name: "Aquawin Warmwasser SOLL"
      state_topic: "tortuga/aquamqtt/hmi/waterTempTarget"
      unit_of_measurement: "°C"

    - name: "Aquawin Zuluft"
      state_topic: "tortuga/aquamqtt/main/supplyAirTemp"
      unit_of_measurement: "°C"
      state_class: measurement

    - name: "Aquawin Verdampfer"
      state_topic: "tortuga/aquamqtt/main/evaporatorAirTemp"
      unit_of_measurement: "°C"
      state_class: measurement

    - name: "Aquawin Verdampfer Lower"
      state_topic: "tortuga/aquamqtt/main/evaporatorAirTempLower"
      unit_of_measurement: "°C"
      state_class: measurement

    - name: "Aquawin Betriebsstunden Gesamt"
      state_topic: "tortuga/aquamqtt/energy/totalHours"
      unit_of_measurement: "h"
      state_class: total

    - name: "Aquawin Betriebsstunden Heizelement"
      state_topic: "tortuga/aquamqtt/energy/totalHeatingElemHours"
      unit_of_measurement: "h"
      state_class: total

    - name: "Aquawin Betriebsstunden Wärmepumpe"
      state_topic: "tortuga/aquamqtt/energy/totalHeatpumpHours"
      unit_of_measurement: "h"
      state_class: total

    - name: "Aquawin Total Energy"
      state_topic: "tortuga/aquamqtt/energy/totalEnergyWh"
      unit_of_measurement: "Wh"
      device_class: energy
      state_class: total

    - name: "Aquawin Power Consumed Heatpump"
      state_topic: "tortuga/aquamqtt/energy/powerHeatpump"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement

    - name: "Aquawin Power Consumed Heating Element"
      state_topic: "tortuga/aquamqtt/energy/powerHeatingElem"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement

    - name: "Aquawin Power Consumed Total"
      state_topic: "tortuga/aquamqtt/energy/powerTotal"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement

    - name: "Aquawin Operation Mode"
      state_topic: "tortuga/aquamqtt/hmi/operationMode"

    - name: "Aquawin Operation Type"
      state_topic: "tortuga/aquamqtt/hmi/operationType"

    - name: "Aquawin Date"
      state_topic: "tortuga/aquamqtt/hmi/date"

    - name: "Aquawin Time"
      state_topic: "tortuga/aquamqtt/hmi/time"

    - name: "Aquawin Fan Speed"
      unit_of_measurement: "rpm"
      state_topic: "tortuga/aquamqtt/main/fanSpeed"

    - name: "Aquawin Active Overrides"
      state_topic: "tortuga/aquamqtt/stats/activeOverrides"

    - name: "Aquawin Override Mode"
      state_topic: "tortuga/aquamqtt/stats/overrideMode"

    - name: "Aquawin Timer Window A"
      state_topic: "tortuga/aquamqtt/hmi/timerWindowA"

    - name: "Aquawin Timer Window B"
      state_topic: "tortuga/aquamqtt/hmi/timerWindowB"

  button:
    - name: "Aquawin SET OperationMode BOOST"
      command_topic: "tortuga/aquamqtt/ctrl/operationMode"
      payload_press: "BOOST"
      qos: 0
      retain: false

    - name: "Aquawin SET OperationMode MAN ECO OFF"
      command_topic: "tortuga/aquamqtt/ctrl/operationMode"
      payload_press: "MAN ECO OFF"
      qos: 0
      retain: false

    - name: "Aquawin SET OperationMode ABSENCE"
      command_topic: "tortuga/aquamqtt/ctrl/operationMode"
      payload_press: "ABSENCE"
      qos: 0
      retain: false

    - name: "Aquawin SET OperationMode RESET"
      command_topic: "tortuga/aquamqtt/ctrl/reset"
      payload_press: ""
      qos: 0
      retain: false

  number:
    - name: "Aquawin SET Target Temperature"
      state_topic: tortuga/aquamqtt/hmi/waterTempTarget
      command_topic: tortuga/aquamqtt/ctrl/waterTempTarget
      min: 40
      max: 62
      step: 1
      unit_of_measurement: "°C"
```

Raw Widget (just add a widget as code)

```yaml
type: vertical-stack
cards:
  - show_name: true
    show_icon: true
    show_state: true
    type: glance
    entities:
      - entity: binary_sensor.aquawin_state_fan
        name: Fan
      - entity: binary_sensor.aquawin_state_heatpump
        name: Pump
      - entity: binary_sensor.aquawin_state_heating_element
        name: Element
      - entity: binary_sensor.aquawin_state_defrost
        name: Defrosting
      - entity: binary_sensor.aquawin_state_external_boiler
        name: Boiler
    title: Windhager AquaWin AWA273
  - type: entities
    entities:
      - entity: sensor.aquawin_operation_mode
        name: Operation Mode
        icon: mdi:cog-outline
      - entity: sensor.aquawin_operation_type
        name: Operation Type
        icon: mdi:cog-clockwise
      - entity: sensor.aquawin_override_mode
        icon: mdi:solar-power
        name: PV Operation Mode
      - entity: sensor.aquawin_timer_window_a
        name: First Time Window
        icon: mdi:clock-time-eight-outline
      - entity: sensor.aquawin_timer_window_b
        name: Second Time Window
        icon: mdi:clock-time-eight-outline
      - entity: sensor.aquawin_warmwasser_ist
        name: Current Temperature
        icon: mdi:coolant-temperature
        secondary_info: none
      - entity: sensor.aquawin_warmwasser_soll
        icon: mdi:coolant-temperature
        name: Destination Temperature
      - entity: sensor.aquawin_zuluft
        name: Supply Air Temperature
        icon: hass:cloud
      - entity: sensor.aquawin_verdampfer
        name: Upper Evaporator
      - entity: sensor.aquawin_verdampfer_lower
        name: Lower Evaporator
      - entity: sensor.aquawin_fan_speed
        name: Fan Speed
        icon: mdi:fan
      - entity: sensor.aquawin_betriebsstunden_gesamt
        icon: mdi:chart-line
        name: Total Operation Hours
      - entity: sensor.aquawin_betriebsstunden_warmepumpe
        name: Total Operation Hours (Pump)
        icon: mdi:chart-line
      - entity: sensor.aquawin_betriebsstunden_heizelement
        name: Total Operation Hourse (Element)
        icon: mdi:chart-line
      - entity: sensor.aquawin_power_consumed_total
        icon: ''
        name: Current Power
      - entity: sensor.aquawin_power_consumed_heatpump
        name: Current Power (Pump)
      - entity: sensor.aquawin_power_consumed_heating_element
        name: Current Power (Element)
      - entity: sensor.aquawin_total_energy
        name: Total Energy Consumption
      - entity: sensor.aquawin_time
        name: Time
        icon: mdi:clock
        secondary_info: last-updated
      - entity: sensor.aquawin_date
        name: Date
        icon: mdi:calendar

```

Another widget acting as test menu, setting or resetting a few overrides:

```yaml
type: entities
entities:
  - entity: button.aquawin_operationmode_absence
    name: ABSENCE
  - entity: button.aquawin_operationmode_boost
    name: BOOST
  - entity: button.aquawin_operationmode_man_eco_off
    name: MAN ECO OFF
  - entity: number.aquawin_target_temperature
  - entity: button.biowin_heizkreislauf_ww_betriebswahl_standby
    name: 'BioWin: HK Standby'
  - entity: button.biowin_heizkreislauf_ww_betriebswahl_warmwasserbetrieb
    name: 'BioWin HK: Warmwasserbetrieb'
  - entity: button.aquawin_operationmode_reset
    name: 'Aquawin: Reset Overrides'
title: TESTMENU
```
And yes, good find: the MQTT topic is wrong in the documentation. I'll fix that ... ;)
