### ISSUE TITLE
Not issue but feedback

### ISSUE THREAD

**Issue by scoudibou** [tspopp/AquaMQTT#14]
Hello @tspopp ,

Just to tell you I've received my PCB today and installed it on Atlantic Explorer V4 and it's working pretty well.
Thank you!

I've a bit changed the MQTT config you gave me to make a unique device in Home Assistant and had 2 PV control switches  : 

```
mqtt:
  binary_sensor:
    - name: "Heating Element"
      state_topic: "aquamqtt/main/stateElement"
      payload_on: "1"
      payload_off: "0"
      icon: mdi:heating-coil
      unique_id: atlantic_state_heatelement
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Heatpump"
      state_topic: "aquamqtt/main/stateHeatpump"
      payload_on: "1"
      payload_off: "0"
      icon: mdi:heat-pump-outline
      unique_id: atlantic_state_heatpump
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Fan"
      state_topic: "aquamqtt/main/stateFan"
      payload_on: "1"
      payload_off: "0"
      icon: mdi:fan
      unique_id: atlantic_state_fan
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "External Boiler"
      state_topic: "aquamqtt/main/stateExtBoiler"
      payload_on: "1"
      payload_off: "0"
      icon: mdi:water-boiler
      unique_id: atlantic_state_extboiler
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Defrost"
      state_topic: "aquamqtt/main/stateDefrost"
      payload_on: "1"
      payload_off: "0"
      icon: mdi:snowflake-melt
      unique_id: atlantic_state_defrost
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
  sensor:
    - name: "Température actuelle"
      state_topic: "aquamqtt/main/waterTemp"
      unit_of_measurement: "°C"
      state_class: measurement
      unique_id: atlantic_state_watertemp
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Température cible"
      state_topic: "aquamqtt/hmi/waterTempTarget"
      unit_of_measurement: "°C"
      unique_id: atlantic_state_watertemp_target
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Température entrée d'air"
      state_topic: "aquamqtt/main/supplyAirTemp"
      unit_of_measurement: "°C"
      state_class: measurement
      unique_id: atlantic_state_supplyair_temp
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Température air évaporé"
      state_topic: "aquamqtt/main/evaporatorAirTemp"
      unit_of_measurement: "°C"
      state_class: measurement
      unique_id: atlantic_state_evaporatorair_temp
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Température air évaporé bas"
      state_topic: "aquamqtt/main/evaporatorAirTempLower"
      unit_of_measurement: "°C"
      state_class: measurement
      unique_id: atlantic_state_evaporatorair_temp_lower
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Heures totales"
      state_topic: "aquamqtt/energy/totalHours"
      unit_of_measurement: "h"
      state_class: total
      unique_id: atlantic_state_total_hours
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Heures Résistance"
      state_topic: "aquamqtt/energy/totalHeatingElemHours"
      unit_of_measurement: "h"
      state_class: total
      unique_id: atlantic_state_total_heatelement_hours
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Heures Pompe à chaleur"
      state_topic: "aquamqtt/energy/totalHeatpumpHours"
      unit_of_measurement: "h"
      state_class: total
      unique_id: atlantic_state_total_heatpump_hours
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Total Energy"
      state_topic: "aquamqtt/energy/totalEnergyWh"
      unit_of_measurement: "Wh"
      device_class: energy
      state_class: total
      unique_id: atlantic_state_total_energy
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Power Consumed Heatpump"
      state_topic: "aquamqtt/energy/powerHeatpump"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      unique_id: atlantic_state_power_heatpump
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Power Consumed Heating Element"
      state_topic: "aquamqtt/energy/powerHeatingElem"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      unique_id: atlantic_state_power_heatelement
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Power Consumed Total"
      state_topic: "aquamqtt/energy/powerTotal"
      unit_of_measurement: "W"
      device_class: power
      state_class: measurement
      unique_id: atlantic_state_power_total
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Operation Mode"
      state_topic: "aquamqtt/hmi/operationMode"
      unique_id: atlantic_state_operationmode
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Operation Type"
      state_topic: "aquamqtt/hmi/operationType"
      unique_id: atlantic_state_operationtype
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Date"
      state_topic: "aquamqtt/hmi/date"
      unique_id: atlantic_state_date
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Time"
      state_topic: "aquamqtt/hmi/time"
      unique_id: atlantic_state_time
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Fan Speed"
      unit_of_measurement: "rpm"
      state_topic: "aquamqtt/main/fanSpeed"
      unique_id: atlantic_state_fanspeed
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Active Overrides"
      state_topic: "aquamqtt/stats/activeOverrides"
      unique_id: atlantic_state_activeoverrides
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Override Mode"
      state_topic: "aquamqtt/stats/overrideMode"
      unique_id: atlantic_state_overridemode
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Timer Window A"
      state_topic: "aquamqtt/hmi/timerWindowA"
      unique_id: atlantic_state_time_windowa
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "Timer Window B"
      state_topic: "aquamqtt/hmi/timerWindowB"
      unique_id: atlantic_state_time_windowb
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
  button:
    - name: "BOOST"
      command_topic: "aquamqtt/ctrl/operationMode"
      payload_press: "BOOST"
      qos: 0
      retain: false
      unique_id: atlantic_ctrl_operationmode_boost
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "MAN ECO OFF"
      command_topic: "aquamqtt/ctrl/operationMode"
      payload_press: "MAN ECO OFF"
      qos: 0
      retain: false
      unique_id: atlantic_ctrl_operationmode_eco
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "ABSENCE"
      command_topic: "aquamqtt/ctrl/operationMode"
      payload_press: "ABSENCE"
      qos: 0
      retain: false
      unique_id: atlantic_ctrl_operationmode_absence
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "RESET"
      command_topic: "aquamqtt/ctrl/reset"
      payload_press: ""
      qos: 0
      retain: false
      unique_id: atlantic_ctrl_reset
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
  number:
    - name: "Target Temperature"
      state_topic: aquamqtt/hmi/waterTempTarget
      command_topic: aquamqtt/ctrl/waterTempTarget
      min: 40
      max: 62
      step: 1
      unit_of_measurement: "°C"
      unique_id: atlantic_ctrl_watertemp_target
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
  switch:
    - name: "PV Mode Pompe à chaleur"
      command_topic: "aquamqtt/ctrl/flagPVModeHeatPump"
      state_topic: "aquamqtt/stats/flagPVModeHeatPump"
      payload_on: "1"
      payload_off: "0"
      unique_id: atlantic_ctrl_pvmode_heatpump
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
    - name: "PV Mode Résistance"
      command_topic: "aquamqtt/ctrl/flagPVModeHeatElement"
      state_topic: "aquamqtt/stats/flagPVModeHeatElement"
      payload_on: "1"
      payload_off: "0"
      unique_id: atlantic_ctrl_pvmode_heatelement
      device:
        identifiers: AquaMQTT
        manufacturer: tspopp
        name: AquaMQTT 
        model: V1
```

I have to think how to optimize the usage of the boiler now :)..

Regards
